# Generated by Django 5.2.17 on 2026-09-23 03:19

import apps.content.validators
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('tag', models.CharField(choices=[('production', 'PRODUCTION'), ('team', 'GURUH LOYIHASI'), ('personal', 'SHAXSIY LOYIHA'), ('learning', "O'QUV LOYIHASI")], default='production', max_length=20)),
                ('problem', models.TextField(validators=[django.core.validators.MaxLengthValidator(600)])),
                ('solution', models.TextField(validators=[django.core.validators.MaxLengthValidator(600)])),
                ('role', models.CharField(max_length=300)),
                ('stack', models.CharField(max_length=200)),
                ('repo_url', models.URLField(blank=True, default='')),
                ('demo_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_published', 'order'], name='project_published_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hero_line_1', models.CharField(default='Kod yozaman.', max_length=60)),
                ('hero_line_2', models.CharField(default='Serverga chiqaraman.', max_length=60)),
                ('about_text', models.CharField(default="Azizillo. Django va Django REST Framework'da backend yozaman. TATU, Software Engineering, 1-kurs.", max_length=300)),
                ('status_text', models.CharField(default='TuitDorm — TATU yotoqxonasini boshqarish tizimi ustida ishlayapman.', max_length=160)),
                ('github_url', models.URLField(blank=True, default='', validators=[apps.content.validators.validate_github_url])),
                ('telegram_url', models.URLField(blank=True, default='', validators=[apps.content.validators.validate_telegram_url])),
                ('linkedin_url', models.URLField(blank=True, default='', validators=[apps.content.validators.validate_linkedin_url])),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, validators=[apps.core.validators.validate_phone])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='site_settings_singleton')],
            },
        ),
    ]
